# Generated by Django 4.2.7 on 2023-12-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEquipment',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Desc', models.TextField()),
                ('condition', models.TextField()),
                ('location', models.TextField()),
                ('available', models.BooleanField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='verified',
        ),
    ]
