# Generated by Django 4.2.7 on 2023-12-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_addequipment_remove_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addequipment',
            name='rental_rate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='addequipment',
            name='type',
            field=models.TextField(default='tractor'),
        ),
        migrations.AddField(
            model_name='addequipment',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addequipment',
            name='Desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addequipment',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
