# Generated by Django 4.2.7 on 2023-12-01 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_addequipment_rental_rate_addequipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addequipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
